[workspace]
members = [
    "collector",
    "collector/benchlib",
    "site",
    "database",
    "database/import-sqlite",
    "database/postgres-to-sqlite",
    "intern",
]
exclude = ["rust/src"]
resolver = "2"

[profile.release.package.site]
debug = 1

[profile.release.package.collector]
debug = 1
